baseURL = "https://sinhak.dev/"
languageCode = "en-us"
title = "The Janus List"
theme = "archie"
copyright = "© Kushagra Sinha"

[params]
    author = "Kushagra Sinha"
    subtitle = "I disclaim thee, o' liability"
    mode = "toggle" # Color mode - light or dark.
    keywords = "blog,developer,personal"
    info = "Software Engineer"
    avatarurl = "/images/avatar.jpg"
    favicon = "/images/favicon-32x32.png"
    useCDN = true

[[params.social]]
    name = "Github"
    icon = "github"
    weight = 1
    url = "https://github.com/j4nu5/"
[[params.social]]
    name = "Twitter"
    icon = "twitter"
    weight = 2
    url = "https://twitter.com/j4nu5/"
[[params.social]]
    name = "LinkedIn"
    icon = "linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/sinhakushagra/"

[[menu.main]]
    name = "articles"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "about"
    weight = 2
    url  = "/about/"

[pagination]
  disableAliases = false
  pagerSize = 3
  path = "page"

[services]
  [services.disqus]
    shortname = "the-janus-list"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    hl_inline = false
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = "gruvbox"
    tabWidth = 4
