baseURL = "https://sinhak.dev/"
languageCode = "en-us"
title = "The Janus List"
theme = "hugo-coder"

paginate = 20

# Highlighting config
pygmentsStyle = "bw"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table"

# External Integrations
googleAnalytics = "UA-24193913-1"
disqusShortname = "j4nu5"

[params]
    author = "Kushagra Sinha"
    description = "Kushagra Sinha's personal website"
    colorscheme = "auto"
    keywords = "blog,developer,personal"
    info = "Software Engineer"
    avatarurl = "images/avatar.jpg"
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/j4nu5/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/j4nu5/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/sinhakushagra/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url  = "/about/"
