baseURL = "https://sinhak.dev/"
languageCode = "en-us"
title = "The Janus List"
theme = "hugo-coder"

# Highlighting config
pygmentsStyle = "bw"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table"

[params]
    author = "Kushagra Sinha"
    description = "Kushagra Sinha's personal website"
    colorscheme = "auto"
    keywords = "blog,developer,personal"
    info = "Software Engineer"
    avatarurl = "images/avatar.jpg"
[[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    url = "https://github.com/j4nu5/"
[[params.social]]
    name = "Twitter"
    icon = "fa-brands fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/j4nu5/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/sinhakushagra/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url  = "/about/"

[pagination]
  disableAliases = false
  pagerSize = 20
  path = 'page'

[services]
  [services.disqus]
    shortname = 'the-janus-list'
